=== mhomaid/kafka-connect-apache-pinot/src/main/resources/specs/spec-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "javaType": "com.yama.kafka.connect.pinot.model.JobSpec",
  "properties": {
    "jobType": {
      "type": "string"
    },
    "inputDirURI": {
      "type": "string"
    },
    "includeFileNamePattern": {
      "type": "string"
    },
    "outputDirURI": {
      "type": "string"
    },
    "overwriteOutput": {
      "type": "boolean"
    },
    "pinotFSSpecs": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "scheme": {
              "type": "string"
            },
            "className": {
              "type": "string"
            }
          },
          "required": [
            "scheme",
            "className"
          ]
        }
      ]
    },
    "recordReaderSpec": {
      "type": "object",
      "properties": {
        "dataFormat": {
          "type": "string"
        },
        "className": {
          "type": "string"
        },
        "configClassName": {
          "type": "string"
        }
      },
      "required": [
        "dataFormat",
        "className",
        "configClassName"
      ]
    },
    "tableSpec": {
      "type": "object",
      "properties": {
        "tableName": {
          "type": "string"
        }
      },
      "required": [
        "tableName"
      ]
    },
    "pinotClusterSpecs": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "controllerURI": {
              "type": "string"
            }
          },
          "required": [
            "controllerURI"
          ]
        }
      ]
    }
  }
}

=== mhomaid/kafka-connect-apache-pinot/src/main/resources/specs/job-spec.json
{
  "jobType": "SegmentCreationAndTarPush",
  "inputDirURI": "/Users/mohamed.homaid/Apache/Pinot/pinot-tutorial/transcript/rawdata/",
  "includeFileNamePattern": "glob:**/*.json",
  "outputDirURI": "/Users/mohamed.homaid/Apache/Pinot/pinot-tutorial/transcript/segments/",
  "overwriteOutput": true,
  "pinotFSSpecs": [
    {
      "scheme": "file",
      "className": "org.apache.pinot.spi.filesystem.LocalPinotFS"
    }
  ],
  "recordReaderSpec": {
    "dataFormat": "json",
    "className": "org.apache.pinot.plugin.inputformat.json.JsonRecordReader",
    "configClassName": "org.apache.pinot.plugin.inputformat.json.JSONRecordReaderConfig"
  },
  "tableSpec": {
    "tableName": "transcript"
  },
  "pinotClusterSpecs": [
    {
      "controllerURI": "http://localhost:9001"
    }
  ]
}
